require("arbab")
require("arbab/lazy")
require("after/plugins/telescope")
require("after/plugins/colorscheme")
require("after/plugins/treesitter")
require("after/plugins/lsp")
require("after/plugins/autoclose")
require("after/plugins/completion")